Pass the request headers from the auth middleware to authenticators.
amalgam8/amalgam8 pull request #341
Opened 2016-10-13 20:28 UTC by craigyam

Update the authenticators to accept a context.  The auth middleware will pass the request headers to the authenticator using the context.

2016-10-16 09:36 UTC, zcahana requested changes

2016-10-16 09:36 UTC, zcahana commented on pkg/auth/authenticator.go
> +import "golang.org/x/net/context"
We should be using the [standard library's context package](https://golang.org/pkg/context/).
It was only introduced in Go 1.7, so we'll need to upgrade our Go version for that.

Given that our previous issues with Go 1.7 has already been resolved (see #266), I'll submit a PR with the Go update, so please rebase your branch on that update.

2016-10-16 09:36 UTC, zcahana commented on pkg/auth/trusted.go
> +func (aut *trustedAuthenticator) Authenticate(token string, ctx ...context.Context) (*Namespace, error) {
By convention, the context should be the first parameter of a function (see [here](https://golang.org/pkg/context/)).
This means that the `...` vararg will also need to go away.

2016-10-16 09:36 UTC, zcahana commented on registry/api/middleware/auth.go
> +	ctx := context.WithValue(context.Background(), auth.ContextHeadersKey, request.Header)
The intended pattern is NOT to initialize a new context with `context.Background()`, but rather to fetch the existing context already associated with the http request. However and unfortunately, the `go-json-rest` package doesn't support context (yet?), and neither exposes the underlying `http.Request`. My suggestion for an interim solution is to add a `ContextMiddleware`, somewhere along the top of the middlewares stack, that initializes a context and puts it in the request's `Env` map, with a well-known key. Later on, we should probably ditch `go-json-rest` in favor a better http framework.

2016-10-16 09:48 UTC, zcahana commented on pkg/auth/authenticator.go
> +import "golang.org/x/net/context"
PR #345 updates go Go 1.7.1. Once merged to master, please rebase.

2016-10-16 10:21 UTC, zcahana commented
P.S. I'm not sure what caused the Travis build failure, but retriggering it seems to have turned it green :)

2016-10-21 04:07 UTC, craigyam commented
Tried to add another commit to address the code review comments but it seems to have done something funny.  Will investigate and work to clean it up.

2016-10-23 06:33 UTC, zcahana approved these changes

2016-10-23 06:34 UTC, zcahana commented
LGTM, thanks @craigyam.

2016-10-23 06:35 UTC, merged