Added service TTL config option
amalgam8/amalgam8 pull request #365
Opened 2016-10-28 18:33 UTC by ijsnellf

Resolves #360.

2016-10-28 18:34 UTC, ijsnellf commented
I have TTL default to 60s right now.

2016-10-30 09:31 UTC, zcahana requested changes

2016-10-30 09:31 UTC, zcahana commented on sidecar/config/config.go
> +	TTL  time.Duration `yaml:"ttl"`
I'm not sure endpoint is the right place for the TTL. In the Registry's API, the TTL and endpoint are both attributes of the registered service instance.

Perhaps we can have the TTL (and later on, hearbeat frequency, maybe) under the `register` attribute:
```yaml
register:
	ttl: 60s
	heartbeat: 20s
```

And ideally, still support the boolean `register` flag that uses default values for ttl/heartbeat:
```yaml
register: true
```

2016-10-30 09:31 UTC, zcahana commented on sidecar/config/config.go
> +			IsInRangeDuration("Service Endpoint TTL", c.Endpoint.TTL, 30*time.Second, 120*time.Second),
I don't see a reason to restrict the TTL that much. How about [10s, 10m]?

2016-10-31 14:28 UTC, ijsnellf commented on sidecar/config/config.go
> +			IsInRangeDuration("Service Endpoint TTL", c.Endpoint.TTL, 30*time.Second, 120*time.Second),
Has registry been modified to support TTLs less than 30s?

2016-10-31 16:19 UTC, zcahana commented on sidecar/config/config.go
> +			IsInRangeDuration("Service Endpoint TTL", c.Endpoint.TTL, 30*time.Second, 120*time.Second),
The registry supports configuration of [min,max] TTL, which defaults to [10s, 10m].

2016-11-01 17:28 UTC, rshriram commented on sidecar/config/config.go
> +	TTL  time.Duration `yaml:"ttl"`
@ijsnellf is this supported yet?

2016-11-01 18:12 UTC, ijsnellf commented on sidecar/config/config.go
> +	TTL  time.Duration `yaml:"ttl"`
No.

2016-12-09 02:41 UTC, rshriram commented
should we can this for the moment?

2016-12-09 16:31 UTC, closed without merging