Zombie Cleanup Re-Org
amalgam8/amalgam8 pull request #423
Opened 2016-11-30 20:32 UTC by GregHanson

pull request resolving issues documented in issue #422 

 - moved the PID=1 logic out of sidecar.go
 - PID=1 propagates signals to child sidecar process
 - PID=1 process shuts down with the same exit code as the child sidecar process
 - uses syscall to see if PID=1 rather than presence of env var

2016-11-30 21:06 UTC, ijsnellf approved these changes

2016-11-30 21:06 UTC, ijsnellf commented on sidecar/supervisor/init.go
> +func shutdown(sig int) {
`func shutdown(code int)`?

2016-12-01 08:56 UTC, zcahana requested changes

2016-12-01 08:56 UTC, zcahana commented on sidecar/supervisor/init.go
> +	cmd := exec.Command("a8sidecar", os.Args[1:]...)
It would be more robust to use `exec.Command(os.Args[0], os.Args[1:]...)`

2016-12-01 08:56 UTC, zcahana commented on sidecar/supervisor/init.go
> +	cmd.Env = os.Environ()
No need to explicitly copy the environment variables, as by default they are inherited from the parent.

2016-12-01 08:56 UTC, zcahana commented on sidecar/sidecar.go
> +	if os.Getpid() == 1 {
Should this be an if-else condition, so that we have a distinct branches for being PID 1 or not?

2016-12-01 08:56 UTC, zcahana commented on sidecar/supervisor/init.go
> +		cmd.Process.Signal(sig)
Race condition here: `cmd.Process` might be nil.

2016-12-01 08:56 UTC, zcahana commented on sidecar/supervisor/init.go
> +	signal.Notify(sigChan, syscall.SIGTERM, syscall.SIGINT)
Forwarding SIGTERM/SIGINT once is not enough - we need to forward any signal (except for SIGCHLD), any time it's received, as long as the child process is alive, and exit only when the child exists.

I would structure the `Init()` method something along this line:
```go
func Init() {
	cmd := ... // build and set up command object
	
	err := cmd.Start()
	if err != nil {
		shutdown(exitCodeFromError(err))
	}
	
	// No we can launch the signal handler
	go handleSignals(cmd.Process)
	
	err = cmd.Wait()
	shutdown(exitCodeFromError(err))
}

func handleSignals(proc os.Process) {
	// Trap all signals
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan)
	
	for sig := range sigChan {
		switch sig {
			case syscall.SIGCHLD:
				reapZombie()
			default:
				forwardSignal(proc, sig)
		}
	}
}
```

2016-12-01 15:42 UTC, GregHanson commented on sidecar/sidecar.go
> +	if os.Getpid() == 1 {
coding convention that golint checks against, it complains when there are return statements in an if/else
```
if PID==1 {

    //do something
    return value
} else {
    //do something else
    return value
}
```
specifically: `amalgam8/sidecar/sidecar.go:75:9: if block ends with a return statement, so drop this else and outdent its block`

2016-12-01 16:31 UTC, ijsnellf approved these changes
LGTM

2016-12-01 20:51 UTC, zcahana commented
I've just realized that we redo issue #401 here, but this time there's a simple solution: instead of calling `cmd.Wait()` (and racing with the SIGCHLD handler), we can inspect the return value of `syscall.Wait4()` to get the PID of the waited-on child, and compare it to `proc.Pid`. If they match, we can `shutdown()`.

2016-12-01 21:18 UTC, GregHanson commented
@zcahana you are right, we would hit that problem only on exit.  I guess the expected race condition is that if SIGCHLD causes us to read the return code before the `cmd.Wait()` does, the PID=1 process would end up exiting with a bad return code.  Based on your comment, is this what you were suggesting?
```func reapZombies(proc *os.Process) {
	for {
		pid, err := syscall.Wait4(-1, nil, syscall.WNOHANG, nil)

		if proc != nil && proc.Pid == pid {
			shutdown(err)
		}
		
		// Spurious wakeup
		if err == syscall.EINTR {
			continue
		}
		logrus.Debug("Zombie reaped")
		// Done
		break
	}
}```

2016-12-04 10:51 UTC, zcahana approved these changes

2016-12-04 10:51 UTC, zcahana commented
LGTM-too. Merging.

2016-12-04 10:52 UTC, merged