A8controller cache
amalgam8/amalgam8 pull request #431
Opened 2016-12-07 16:44 UTC by shlomiti

This PR adds a cache for rules fetching. Sidecar main now uses this cache for A8. This is similar to the caching mechanism we have for the A8 registry fetch.

2016-12-07 16:50 UTC, rshriram commented
This is unrelated, and the previous PR got merged before I could respond. Please remove the *-wip.json from the api package.. We don't need it.

2016-12-07 17:07 UTC, rshriram requested changes
Can we move the cache to the pkg/ as its generic for different rules backends.

2016-12-08 07:16 UTC, zcahana commented
@rshriram the `*-wip.json` is indeed unrelated. I removed it in a separate PR #435.

2016-12-08 07:18 UTC, zcahana commented
Also, regarding the generic cache - this also applies to the a8 registry caching client, which can be generic in the same manner. Given that we don't want to mix registry stuff in this PR, I'll submit another one with the proposed changes.

2016-12-08 07:18 UTC, zcahana commented
Otherwise, LGTM.

2016-12-08 12:12 UTC, rshriram approved these changes

2016-12-08 12:12 UTC, merged

2016-12-11 08:27 UTC, zachidan commented
The cache.ListRules method should skip the api.FilterRules call if the provided filter is either nil or empty.

2016-12-11 10:21 UTC, zcahana commented
@zachidan addressed in #440.