Sidecar TLS support
amalgam8/amalgam8 pull request #437
Opened 2016-12-08 19:57 UTC by paulben

2016-12-08 22:07 UTC, ijsnellf requested changes
Some comments and requests...

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/config/config.go
> +	ProxyConfig ProxyConfig `yaml:"proxyconfig"`
`yaml:"proxy_config"` to keep the naming scheme consistent.

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/config/proxy_config.go
> +type a8ServicesNginxConfData struct {
Prefixing structs and functions with `a8` or `Amalgam8` inside the Amalgam8 repository is unnecessary and can make code harder to read. Could you refactor accordingly?

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/config/proxy_config.go
> +	logrus.Debug("genNginxA8ServicesConf " + strconv.FormatBool(c.Proxy) + " " + strconv.FormatBool(c.ProxyConfig.TLS))
Remove or replace with a more informative message of the form `logrus.Debug("Generating services configuration.")`

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/config/proxy_config.go
> +	if err != nil {
Style tip:
`if err := goTemplate.Execute(file, data); err != nil {`

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/config/proxy_config.go
> +	file, err := os.Create(targetFile)
Lines 73-78 are unnecessary because `os.Create(targetFile)` will overwrite any existing files. See: https://golang.org/pkg/os/#Create

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/nginx/conf/amalgam8-services.conf.tmpl
> +include /etc/nginx/amalgam8-access-logging.conf;
@rshriram: Should the comments about how to configure this file be removed, since this entire config file is automatically generated?

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/sidecar.go
> -		return controllerclient.NewCache(controllerConf)
This looks like an accidental change. The change reverts this code to an earlier version. Please remove this change.

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/register/healthcheck/http.go
> +	//if conf.UpstreamTrustPath != "" {
Remove this commented out code.

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/config/proxy_config.go
> +func (c *Config) GenProxyConfig() error {
The generation code in this file should be moved to `sidecar/proxy/nginx` and either be standalone functions or part of a struct or interface, not member functions of `sidecar/config/Config`.

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/config/flags.go
>  	cli.StringFlag{
Probably a better candidate for `cli.BoolFlag`.

2016-12-08 22:07 UTC, ijsnellf commented on sidecar/sidecar.go
> +	}
The logic for generating the initial NGINX config should be somewhere in the `Run` function, not at the top level here in `sidecarCommand`.

2016-12-09 00:28 UTC, paulben commented on sidecar/config/config.go
> +	ProxyConfig ProxyConfig `yaml:"proxyconfig"`
Consistent with what? I modeled it after dnsconfig.

2016-12-09 00:32 UTC, paulben commented on sidecar/config/proxy_config.go
> +type a8ServicesNginxConfData struct {
I agree that in general an a8 prefix is unnecessary. In this case the a8Services prefix is specifically intended to be descriptive of the target file: amalgam8-services.conf.

2016-12-09 00:34 UTC, paulben commented on sidecar/config/proxy_config.go
> +	if err != nil {
Yep, good point.

2016-12-09 00:59 UTC, paulben commented on sidecar/sidecar.go
> -		return controllerclient.NewCache(controllerConf)
Oops. Good catch. Thank you.

2016-12-09 00:59 UTC, paulben commented on sidecar/register/healthcheck/http.go
> +	//if conf.UpstreamTrustPath != "" {
Yep.

2016-12-09 01:07 UTC, paulben commented on sidecar/config/flags.go
>  	cli.StringFlag{
Indeed.

2016-12-09 01:17 UTC, paulben commented on sidecar/sidecar.go
> +	}
I'm curious where the envoy config is being generated? If that's in `Run` then the nginx config should be generated there also. 

But given that this is the 1st dynamic generation of nginx config it seems to me to be a subjective/philosphical call: 
- Is proxy config generation part of the part of pre-Run config processing? 
- Or is it part of the Run phase?

Functionally the outcome seems identical.

2016-12-09 01:29 UTC, paulben commented on sidecar/config/proxy_config.go
> +func (c *Config) GenProxyConfig() error {
Can't say I disagree. As I'm not involved in the envoy design/code it's hard for me to know the best way to fit this in. 

Could we start with this and then you guys decide the best place/structure for it in the context of the envoy changes? And you refactor as appropriate? 

It seems useful to get this in the stream sooner rather than later to avoid more merging delays/commits, particularly given that this is a question of optimal code structure rather than a functional issue.

2016-12-09 01:29 UTC, paulben commented on sidecar/config/proxy_config.go
> +	logrus.Debug("genNginxA8ServicesConf " + strconv.FormatBool(c.Proxy) + " " + strconv.FormatBool(c.ProxyConfig.TLS))
Ok.

2016-12-09 01:48 UTC, rshriram requested changes

2016-12-09 01:48 UTC, rshriram commented on sidecar/nginx/conf/amalgam8-services.conf.tmpl
> +       ## For using the A8 proxy as a gateway with SSL support
Remove these comments please

2016-12-09 01:48 UTC, rshriram commented on sidecar/nginx/conf/amalgam8-services.conf.tmpl
> +         # Add proxy SSL verification directives here:
Change this comment to 
```nginx
####DO NOT CHANGE#####
{{.CACertPath}}
######################
```

Apply the same style to other parts of the config that have the template code.

2016-12-09 01:51 UTC, paulben commented on sidecar/config/proxy_config.go
> +	file, err := os.Create(targetFile)
Would that be the "...truncating it if it already exists." part in the referenced doc?

I'll code it up and give it a shot given that the file will exist as the product is today.

2016-12-09 03:28 UTC, rshriram commented on sidecar/config/proxy_config.go
> +type a8ServicesNginxConfData struct {
Lets please avoid using a8 inside the code. The code is not bound to that filename. You can rename that file and fix nginx.conf and things would stil work.

2016-12-09 05:28 UTC, paulben commented on sidecar/nginx/conf/amalgam8-services.conf.tmpl
> +       ## For using the A8 proxy as a gateway with SSL support
Done.

2016-12-09 05:28 UTC, paulben commented on sidecar/sidecar.go
> -		return controllerclient.NewCache(controllerConf)
Done.

2016-12-09 05:29 UTC, paulben commented on sidecar/sidecar.go
> +	}
Moved to Run.

2016-12-09 05:30 UTC, paulben commented on sidecar/nginx/conf/amalgam8-services.conf.tmpl
> +include /etc/nginx/amalgam8-access-logging.conf;
Done (see @rshriram's comment below)

2016-12-09 05:30 UTC, paulben commented on sidecar/config/proxy_config.go
> +	if err != nil {
Done.

2016-12-09 05:30 UTC, paulben commented on sidecar/config/proxy_config.go
> +	file, err := os.Create(targetFile)
Done.

2016-12-09 05:30 UTC, paulben commented on sidecar/config/proxy_config.go
> +	logrus.Debug("genNginxA8ServicesConf " + strconv.FormatBool(c.Proxy) + " " + strconv.FormatBool(c.ProxyConfig.TLS))
Done.

2016-12-09 05:31 UTC, paulben commented on sidecar/config/proxy_config.go
> +type a8ServicesNginxConfData struct {
Done.

2016-12-09 05:32 UTC, paulben commented on sidecar/register/healthcheck/http.go
> +	//if conf.UpstreamTrustPath != "" {
Done.

2016-12-09 05:33 UTC, paulben commented on sidecar/config/flags.go
>  	cli.StringFlag{
Done.

2016-12-09 13:07 UTC, rshriram commented on sidecar/sidecar.go
> -		return controllerclient.NewCache(controllerConf)
Where ? I still see it in the diff.

2016-12-09 13:09 UTC, rshriram commented on sidecar/config/proxy_config.go
> +	file, err := os.Create(targetFile)
I don't see it in the diff. Perhaps you forgot to commit?

2016-12-09 13:09 UTC, rshriram submitted a review, later dismissed
Two comments (things you probably forgot to commit).

2016-12-09 15:55 UTC, ijsnellf submitted a review, later dismissed

2016-12-09 15:55 UTC, ijsnellf commented on sidecar/config/proxy_config.go
> +func (c *Config) GenProxyConfig() error {
> Could we start with this and then you guys decide the best place/structure for it in the context of the envoy changes? And you refactor as appropriate?

My comment above suggests the appropriate place to put the functions/structure. If you want this PR to be merged, please change it.

2016-12-12 16:13 UTC, merged