Add example automation scripts.
amalgam8/amalgam8 pull request #455
Opened 2017-01-04 23:25 UTC by craigyam

- Add startup/cleanup and bookinfo demo scripts.
- Add example targets to the Makefile.
- Add HelloWorld test automation changes
- Add scripts to setup kubernetes environment for testing.
- Add make examples to the before_deploy. Also, check the branch
name 'example_automation' as that's the current branch name for
this work.
- Need to install the dependencies (docker-compose, a8ctl etc)
when doing the deploy since make examples needs them.
- Automate the helloworld demo.
- Add traffic-step and traffic-abort and update beta cli binary.
- Tag images with the branch version number and support the cli
recipe-run command.
- Push bookinfo examples to dockerhub.
- Dump debug in bookinfo script after failures.
- Reset the rules on failures to see if that resolves the issues
with the nginx service reporting as down.
- Add additional retries to the remaining testcases.
- Add k8s commands when dump debug info.
- Seeing other failures during some of the other testcases that
will probably be fixed by retries.
- Use kubectl commands for k8s demo runs when dumping debug data.
- Add the start/stop makefile targets to set the version. Fix the
version variable name in the push to dockerhub script.
- Add make targets to stop/start bookinfo.
- Fix version tag for examples images.
- Move push to after_deploy in travis.yaml.
- The examples are running twice as the push script is considered
another deploy.  Move it to the after_deploy section.
Also, add stop/start makefile support for bookinfo.
- Call push script in after_deploy.
- Update push script and move versioned yamls to subdirs.
- Merge in examples updates to change to k8s registry.
- Update with elasticsearch changes.
- Build the cli before running the tests.
- Dockerize before running examples

2017-01-05 15:51 UTC, rshriram requested changes
@craigyam this patch is super huge. Can you break this up into smaller focussed commits that make things easier to review?

There is also an awful lot of duplication in the test scripts between testing and examples/test-scripts folder. Is there any way to deduplicate the stuff?

2017-01-06 17:18 UTC, craigyam commented
@rshriram @ijsnellf 
I have broken up the commit into smaller pieces so hopefully that makes reviewing a little easier.  I talked to @gicaceres about reusing code between examples and testing.  He's currently making a number of updates to testing so we thought we'd work together after he's done to see if there is a good way to share common code (in a separate pull request).  Sound good?

2017-01-10 22:16 UTC, rshriram requested changes
@craigyam Sorry for the delayed review. There is a lot of duplication between this and the test infrastructure we currently have. IF we take this patch as is, it will get immensely complicated to maintain two sets of scripts that do exactly the same thing.

I suggest reusing the testing scripts in the testing/ folder. Add additional code there to test out the apps in examples/ instead of testing out the apps in testing/apps/. 

Once that is done, the only other change that you would have to tackle is handling JSON (testapps) vs html (existing examples). I think this should be an easy fix.

With regard to helloworld, I suggest doing some simple statistics (50/50) and testing it over 100, and seeing if each version gets atleast 40+ hits.

2017-01-10 22:16 UTC, rshriram commented on examples/apps/bookinfo/build-services.sh
> +	APP_VER="unknown"
we cannot build with unknown version. We should rather exit

2017-01-10 22:16 UTC, rshriram commented on .travis.yml
>        fi
I think we already have jq in the travis vm. Our existing tests use it IIRC. right?

2017-01-10 22:16 UTC, rshriram commented on .travis.yml
> +    - ./scripts/push_dockerhub.sh
Why did you remove the check for version-tagged commit ?

2017-01-10 22:16 UTC, rshriram commented on Makefile
> +	@examples/test-scripts/docker/test-docker-helloworld.sh $(APP_VER_ABBR) || exit 1
You don't need `exit 1` in make file.. It should exit by default.

2017-01-10 22:16 UTC, rshriram commented on examples/k8s-start-helloworld.sh
> +sed -e "s/{APP_VER}/$APP_VER/" $SCRIPTDIR/test-scripts/kubernetes/k8s-helloworld.yaml | kubectl create -f -
Is this file just for testing or for release? We don't need this file for release.

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/bookinfo.sh
> +#
reuse with testing/scripts ?

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/docker/cleanup-helloworld.sh
> +
why do we need this file?

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/docker/docker-bookinfo.yaml
> +  environment:
Our test environment docker file is 99% identical. I suggest we export a bunch of env vars and use that to test actual example apps or test apps, using one single docker file.

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/docker/run-controlplane-docker.sh
> +fi
Kill file. Please see comments on #463

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/docker/test-docker-bookinfo.sh
> +exit $RC
Kill file. Please see comments on #463

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/gremlin-script/load-productpage.sh
> +curl -s -b 'foo=bar;user=jason;x' http://localhost:32000/productpage/productpage > /dev/null
kill. This is a duplicate.

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/helloworld.sh
> +        # Test failed, routing outside 75%/25%, try again
I am not sure you can rely on such accurate statistics, esp given that choice of versions is random. You might have to run it 1000 times.. Which would take forever.

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/kubernetes/cleanup-bookinfo.sh
> +$SCRIPTDIR/run-controlplane-kubernetes.sh stop
Kill file. Please see comments on #463

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/kubernetes/cleanup-helloworld.sh
> +$SCRIPTDIR/run-controlplane-kubernetes.sh stop
kill file

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/kubernetes/cleanup-helloworld.sh
> +$SCRIPTDIR/run-controlplane-kubernetes.sh stop
Move the one liner code into the parent file.

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/kubernetes/install-kubernetes.sh
> +sleep 30
reuse from testing

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/kubernetes/k8s-bookinfo.yaml
> +          value: productpage:version=v1
same comment as docker file.

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/kubernetes/k8s-helloworld.yaml
> +          value: helloworld:version=v2
If this is the only difference in all these files, why can't we use bunch of environment variables ?

2017-01-10 22:16 UTC, rshriram commented on examples/test-scripts/kubernetes/run-controlplane-kubernetes.sh
> +fi
kill file.. see #463

2017-01-10 22:16 UTC, rshriram commented on scripts/push_dockerhub.sh
> +
Shouldn't we follow the same convention as sidecar, controller and registry?

2017-01-11 16:37 UTC, closed without merging