Envoy Proxy with Discovery Support
amalgam8/amalgam8 pull request #465
Opened 2017-01-10 19:21 UTC by GregHanson

- Dockerfile.sidecar.envoy uses amalgam8/envoy image until lyft/envoy image is updated to their latest release

 - Default proxy is still NGINX until envoy merges in regex header support: https://github.com/lyft/envoy/pull/335

2017-01-10 23:04 UTC, rshriram commented
conflicts. please merge.

2017-01-11 04:04 UTC, rshriram commented
Please use `^(.*?;)?(user=jason)(;.*)?$` as the regex in envoy config for gremlin tests. You might have to modify the script in testing/test-scripts/demo-script.sh to pass in the header value in appropriate format. @gicaceres might probably have to remove any prefixing that is being done automatically by the CLI.

2017-01-11 17:49 UTC, ijsnellf commented
@rshriram's comment was addressed here: https://github.com/amalgam8/amalgam8/pull/466

2017-01-11 22:40 UTC, ijsnellf reviewed
SDS comments.

2017-01-11 22:40 UTC, ijsnellf commented on sidecar/config/flags.go
> +	cli.IntFlag{
Do we want to expose the SDS port? The only thing that uses it is Envoy, so it seems like something we might want to hide (an implementation detail).

2017-01-11 22:40 UTC, ijsnellf commented on sidecar/discovery/server.go
> +	if s.listener != nil {
Possible race-condition with `s.listener`, since it is assigned in `serve` and accessed here in `Stop`.

2017-01-11 22:40 UTC, ijsnellf commented on sidecar/discovery/server.go
> +	router, err := rest.MakeRouter(routes...)
This could be simplified to:
`rest.MakeRouter(discoveryAPI.Routes()...)`
and the `routes` var could be removed.

2017-01-12 19:50 UTC, GregHanson commented on sidecar/config/flags.go
> +	cli.IntFlag{
I think we wanted it left here so we explicitly show that port 6500 is used for the discovery api in order to avoid port conflicts

2017-01-12 21:53 UTC, ijsnellf commented
It keeps hitting this in Travis:
```No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated```

2017-01-13 14:47 UTC, rshriram approved these changes

2017-01-13 15:11 UTC, rshriram requested changes

2017-01-13 15:11 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +	"\"timestamp_in_ms\":\"%START_TIME%\", " +
s/timestamp_in_ms/start_time/
because start_time is in a different format.

2017-01-13 15:11 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +	"\"$a8_trace_key\":\"NEED\", " +
remove this line for the moment. Envoy has X-Request-ID which we can piggyback on for the moment.

2017-01-13 15:11 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +	"\"upstream_time\":\"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\", " +
Duplicate of upstream_response_time.

2017-01-13 15:11 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +	"\"src\": \"NEED\", " +
This needs to be generated in the Go code. We already know the src name, don't we? Thats how we filter rules and generate the correct config.

2017-01-13 15:11 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +							URL: "tcp://127.0.0.1:6500",
Bug. We have a configurable discovery port, but this one is hard coded.

2017-01-13 23:14 UTC, rshriram approved these changes

2017-01-13 23:15 UTC, merged