Update makefile with examples target and add versioning.
amalgam8/amalgam8 pull request #472
Opened 2017-01-17 22:54 UTC by craigyam

- Add test.examples makefile target
- Version the examples images

2017-01-18 17:03 UTC, gicaceres requested changes

2017-01-18 17:03 UTC, gicaceres commented on testing/generate_example_yaml.sh
> +TAG=$1
we should exit if TAG is empty

2017-01-18 17:03 UTC, gicaceres commented on testing/kubernetes/test-kubernetes.sh
> +A8_RELEASE=$2
exit if empty

2017-01-18 17:03 UTC, gicaceres commented on testing/docker/test-docker.sh
> +export A8_RELEASE=$2
We should exit if empty

2017-01-18 17:29 UTC, craigyam commented on testing/generate_example_yaml.sh
> +TAG=$1
Done

2017-01-18 17:29 UTC, gicaceres approved these changes
LGTM

2017-01-18 17:29 UTC, craigyam commented on testing/kubernetes/test-kubernetes.sh
> +A8_RELEASE=$2
Validated this in the test suite check section.

2017-01-18 17:37 UTC, craigyam commented
Need to update the bluemix.cfg as well.  Will generate it in the generate_example_yaml.sh script.

2017-01-18 17:38 UTC, gicaceres requested changes
Need to update bluemix examples

2017-01-18 20:37 UTC, craigyam commented
Removed the yamls from the examples directory as they are generated by testing/generate_example_yaml.sh (make build.exampleapps).  They should still be included in the zip file generated by make release with the appropriate version number.

2017-01-18 22:11 UTC, gicaceres approved these changes
LGTM

2017-01-18 23:13 UTC, rshriram approved these changes
LGTM. Have you verified that when you tag a commit in master, and run make examples, you get the example YAML files in examples/folder?

2017-01-19 14:43 UTC, craigyam commented
@rshriram I haven't tested it out in master, but I tested out the follow up push_dockerhub.sh changes (in a different fork) and verified that the yamls are generated with the version numbers included.

2017-01-20 15:42 UTC, merged