[WIP] first pass at adding circuit breakers to envoy
amalgam8/amalgam8 pull request #492
Opened 2017-01-30 19:48 UTC by GregHanson

2017-01-30 19:57 UTC, GregHanson commented
@rshriram `timeout` and `retries` are in the rules schema under the `Backend`s field.  Should I add the remaining circuit breaker fields:

```
	MaxConnections    int `json:"max_connections,omitempty"`
	MaxPendingRequest int `json:"max_pending_requests,omitempty"`
	MaxRequests       int `json:"max_requests,omitempty"`
```

under the Backend struct as well?  Or should I make a substruct in Backend?  Not sure if adding the substruct in the rule schema will break any retry/timeout logic in the nginx lua code

2017-01-30 20:51 UTC, rshriram requested changes

2017-01-30 20:51 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +		}
To avoid this format conversion, I suggest we change the rules schema to use timeout_budget_ms. What do you think?

2017-01-30 20:51 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +			}
hard coding?

2017-01-30 20:56 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +			}
See @GregHanson's comment above.

2017-01-30 20:57 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +		}
That will mean we have to do the inverse conversion in NGINX. Do we care about keeping NGINX up to date?

2017-01-30 20:59 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +		}
no..

2017-01-31 21:26 UTC, ijsnellf requested changes

2017-01-31 21:26 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +				cluster.ConnectTimeoutMs = int(backend.Hystrix.TimeoutMS * 1000)
It is confusing that the field is called `timeout_ms`, but apparently contains float seconds. Either we should switch to a field name of just `timeout`, or we should have `timeout_ms` contain integer milliseconds.

2017-01-31 21:26 UTC, ijsnellf commented on pkg/api/rules-schema.json
> +              "description": "Connect/read/write timeout when talking to an instance. Default is nginx's timeout (60s). Unit is in seconds (e.g, 1.234s)",
Remove reference to NGINX.

2017-01-31 21:26 UTC, ijsnellf commented on pkg/api/rules-schema.json
> +              "description": "Maximum number of retries to connect to a backend",
Mention defaults?

2017-01-31 21:26 UTC, ijsnellf commented on pkg/api/rules-schema.json
> +              "description": "Maximum number of retries to connect to a backend",
Same comment for everything below...

2017-01-31 21:26 UTC, ijsnellf commented on sidecar/proxy/envoy/resources.go
> +	Hystrix                  CircuitBreaker   `json:"circuit_breaker"`
Field name should match the JSON tag to reduce confusion.

2017-01-31 21:26 UTC, ijsnellf commented on sidecar/proxy/envoy/resources.go
> +	Timeout       string   `json:"timeout_ms,omitempty"`
Was this added accidentally? I don't see it used anywhere, and it is type `string`.

2017-01-31 21:26 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +		if backend.Hystrix != nil {
Put this in its own function?

2017-01-31 21:26 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +	clusterMap := make(map[string]*api.Backend)
What about clusters with more than one backend?

2017-01-31 21:41 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +				cluster.ConnectTimeoutMs = int(backend.Hystrix.TimeoutMS * 1000)
I agree. We should change the json schema spec to timeout_ms and use timeout ms everywhere.

2017-01-31 21:41 UTC, rshriram commented on pkg/api/rules-schema.json
> +              "description": "Connect/read/write timeout when talking to an instance. Default is nginx's timeout (60s). Unit is in seconds (e.g, 1.234s)",
and say its in milliseconds

2017-02-01 14:09 UTC, GregHanson commented on sidecar/proxy/envoy/manager.go
> +				cluster.ConnectTimeoutMs = int(backend.Hystrix.TimeoutMS * 1000)
@rshriram changing this mean changing all of our docs for bookinfo where we tell everyone to create a 7 second delay - still want me to go forward with that?

2017-02-01 15:00 UTC, rshriram commented on sidecar/proxy/envoy/manager.go
> +				cluster.ConnectTimeoutMs = int(backend.Hystrix.TimeoutMS * 1000)
On second thought, I take it back. Lets revert to using consistent "timeout".. and eliminate all the _ms and MS stuff. In an future PR, we can revisit changing all these to milliseconds.

2017-02-01 19:01 UTC, GregHanson commented
Here is what a sample rule will look like with the new schema:

```
    {
      "id": "1e161ec1-b2ce-4518-a031-29ee56645918",
      "priority": 1,
      "destination": "productpage",
      "route": {
        "backends": [
          {
            "tags": [
              "version=v1"
            ],
            "resilience": {
              "max_connections": 4,
              "max_requests": 88,
              "consecutive_errors": 9,
              "max_requests_per_connection": 1021
            }
          }
        ],
        "tcp_connect_timeout": 0.5,
        "max_retries": 14
      }
    }
```

2017-02-01 19:05 UTC, GregHanson commented
Here is what the sample envoy.json file will look like:

```
{
  "runtime": {
    "symlink_root": "/etc/envoy/runtime/routing",
    "subdirectory": "traffic_shift"
  },
  "listeners": [
    {
      "port": 6379,
      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "ingress_http",
            "generate_request_id": true,
            "add_user_agent": true,
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "backend",
                  "domains": [
                    "*"
                  ],
                  "routes": [
                    {
                      "runtime": {
                        "key": "reviews._:version=v1",
                        "default": 0
                      },
                      "prefix": "/reviews/",
                      "prefix_rewrite": "/",
                      "cluster": "reviews:version=v1",
                      "retry_policy": {
                        "retry_on": "5xx,connect-failure,refused-stream"
                      }
                    },
                    {
                      "runtime": {
                        "key": "productpage._:version=v1",
                        "default": 0
                      },
                      "prefix": "/productpage/",
                      "prefix_rewrite": "/",
                      "cluster": "productpage:version=v1",
                      "timeout_ms": 500,
                      "retry_policy": {
                        "retry_on": "5xx,connect-failure,refused-stream",
                        "num_retries": 14
                      }
                    }
              ]
            },
            "filters": [
              {
                "type": "decoder",
                "name": "router",
                "config": {
                  "dynamic_stats": false
                }
              }
            ],
            "access_log": [
              {
                "path": "/var/log/a8_access.log",
                "format": "{\"status\":\"%RESPONSE_CODE%\", \"start_time\":\"%START_TIME%\", \"request_time\":%DURATION%, \"upstream_response_time\":\"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\", \"src\":\"gateway:version=none\", \"dst\":\"%UPSTREAM_CLUSTER%\", \"gremlin_recipe_id\":\"-\", \"message\":\"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %RESPONSE_CODE%\", \"module\":\"ENVOY\", \"method\":\"%REQ(:METHOD)%\", \"path\":\"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\", \"protocol\":\"%PROTOCOL%\", \"response_flags\":\"%RESPONSE_FLAGS%\", \"x_forwarded\":\"%REQ(X-FORWARDED-FOR)%\", \"user_agent\":\"%REQ(USER-AGENT)%\", \"request_id\":\"%REQ(X-REQUEST-ID)%\", \"auth\":\"%REQ(:AUTHORITY)%\", \"upstream_host\":\"%UPSTREAM_HOST%\"}\n"
              }
            ]
          }
        }
      ]
    }
  ],
  "admin": {
    "access_log_path": "/var/log/envoy_admin.log",
    "port": 8001
  },
  "cluster_manager": {
    "clusters": [
      {
        "name": "details:version=v1",
        "service_name": "details:version=v1",
        "connect_timeout_ms": 1000,
        "type": "sds",
        "lb_type": "round_robin",
        "circuit_breaker": {},
        "outlier_detection": {
          "max_ejection_percent": 100
        }
      },
      {
        "name": "productpage:version=v1",
        "service_name": "productpage:version=v1",
        "connect_timeout_ms": 1000,
        "type": "sds",
        "lb_type": "round_robin",
        "max_requests_per_connection": 1021,
        "circuit_breaker": {
          "max_connections": 4,
          "max_requests": 88
        },
        "outlier_detection": {
          "consecutive_5xx": 9,
          "max_ejection_percent": 100
        }
      }
    ],
    "sds": {
      "cluster": {
        "name": "sds",
        "connect_timeout_ms": 1000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "max_requests_per_connection": 1,
        "hosts": [
          {
            "url": "tcp://127.0.0.1:6500"
          }
        ]
      },
      "refresh_delay_ms": 1000
    }
  }
}
```

Note that productpage `route` and `cluster` have the fields configured while the other services demonstrate the default settings

2017-02-01 20:08 UTC, rshriram requested changes

2017-02-01 20:08 UTC, rshriram commented on pkg/api/rule.go
> +	TCPConnectTimeout float64   `json:"tcp_connect_timeout,omitempty"`
HttpReqTimeout

2017-02-01 20:08 UTC, rshriram commented on pkg/api/rule.go
>  }
HttpReqRetries

2017-02-01 20:08 UTC, rshriram commented on pkg/api/rules-schema.json
> +          "description": "Connect/read/write timeout when talking to a route. Default is 15. Unit is in seconds.",
http_req_timeout
Timeout for a HTTP request. Includes retries as well. Unit is in floating point seconds. Default 15.0s

2017-02-01 20:08 UTC, rshriram commented on pkg/api/rules-schema.json
> +          "description": "Maximum number of retries to connect to a route.  Defaults to 1.",
http_req_retries
Number of retries for a given request.  The interval between retries will be determined automatically (25ms+). Actual number of retries attempted depends on the http_req_timeout

2017-02-01 20:31 UTC, rshriram approved these changes

2017-02-01 21:08 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +		if backend.Resilience != nil {
No function? That's ok. That's fine.

2017-02-01 21:20 UTC, merged