Load Balancing Algorithm Options Added
amalgam8/amalgam8 pull request #494
Opened 2017-01-31 20:27 UTC by kimikowang

2017-01-31 21:30 UTC, ijsnellf commented on pkg/api/rule.go
> +	Lb_type string 	 `json:"lb_type,omitempty"`
style: `LbType`

2017-02-03 03:27 UTC, rshriram requested changes
You still have to pass this to envoy config right?
Can you verify that the generated config file for envoy actually has the right load balancing algorithm?

2017-02-07 23:45 UTC, rshriram requested changes
Please remove productpage binary and the cli/i18n/resources.go. Otherwise it looks good.

2017-02-07 23:46 UTC, kimikowang commented
Changes have been made to sidecar/proxy/envoy/manager.go, where LbType value in backend rule will be included in cluster building to generate the config file.

2017-02-07 23:47 UTC, rshriram commented
See my comment above. You have included irrelevant files in your commit.

2017-02-08 00:20 UTC, rshriram requested changes
And you added another binary.

2017-02-08 00:21 UTC, rshriram reviewed
i18n_resources.go is still there.

2017-02-08 19:19 UTC, rshriram approved these changes

2017-02-08 20:08 UTC, merged