helloworld YAML and application change for k8s
amalgam8/amalgam8 pull request #504
Opened 2017-02-07 15:45 UTC by elevran

2017-02-07 15:47 UTC, rshriram commented on examples/apps/helloworld/app.py
> +        elif os.environ.get('A8_HELLO_VERSION'):
How about just SERVICE_VERSION ? The example will be generic enough to be re-used elsewhere.

2017-02-07 15:55 UTC, elevran commented on examples/apps/helloworld/app.py
> +        elif os.environ.get('A8_HELLO_VERSION'):
Resubmitted with A8_SERVICE_VERSION as envvar name

2017-02-07 15:58 UTC, craigyam commented on examples/apps/helloworld/app.py
> +    global version
Is there a reason version is global?  Could you just initialize version='UNVERSIONED' and then remove the if not checks?

2017-02-07 15:58 UTC, craigyam commented on examples/apps/helloworld/app.py
>      response.set_cookie('version', json.dumps(service_version))
This should be version instead of json.dumps(service_version).

2017-02-07 16:01 UTC, rshriram requested changes

2017-02-07 16:01 UTC, rshriram commented on examples/k8s/k8s-controlplane.yaml
> +# Copyright 2016-2017 IBM Corporation
please move this file to testing/kubernetes/k8s-controlplane.yaml
and then
in testing/run_tests.sh and testing/build_and_run.sh
comment out the following lines

```bash
if [ -z "$A8_TEST_K8S" ]; then
    A8_TEST_K8S="true"
fi
```

This way, we would only be testing docker examples, until the K8S stuff is complete. However, once the K8S stuff is complete, its a simple matter of uncommenting this code. Everything else is taken care of for you. Including producing the YAML files for the end user.

2017-02-07 16:01 UTC, rshriram commented on examples/k8s/k8s-helloworld-25p-v2.yaml
> +# Copyright 2017 IBM Corporation
Move to testing/test-scripts/k8s-helloworld-v1-v2-route-rules.yaml

2017-02-07 16:01 UTC, rshriram commented on examples/k8s/k8s-helloworld-default-v1.yaml
> +# Copyright 2017 IBM Corporation
move to testing/test-scripts/k8s-helloworld-default-route-rules.yaml

2017-02-07 16:01 UTC, rshriram commented on examples/k8s/k8s-helloworld.yaml
> +# Copyright 2017 IBM Corporation
overwrite testing/kubernetes/helloworld.yaml

2017-02-07 16:01 UTC, rshriram commented on examples/k8s/k8s-helloworld-default-v1.yaml
> +# Copyright 2017 IBM Corporation
and please add a note about customizing the tests for kubernetes, in  testing/test-scripts/helloworld.sh above the following code snippet.
```bash
 echo "Set/verify the Hello World default route to v1"
 echo "  Invoking a8ctl to set the default route"
 $A8CLI rule-create -f $SCRIPTDIR/helloworld-default-route-rules.json > /tmp/a8ctl_output.txt
```

2017-02-07 16:01 UTC, rshriram commented on examples/k8s/k8s-helloworld-25p-v2.yaml
> +# Copyright 2017 IBM Corporation
and please add a note about customizing the tests for kubernetes, in  testing/test-scripts/helloworld.sh above the following code snippet (75/25 case)
```bash
 echo "Set/verify the Hello World route to 75%/v1 25%/v2"
    echo "  Invoking a8ctl to set a rule to split the traffic."
    $A8CLI rule-create -f $SCRIPTDIR/helloworld-v1-v2-route-rules.json > /tmp/a8ctl_output.txt
```

2017-02-07 16:14 UTC, elevran commented on examples/apps/helloworld/app.py
> +    global version
not that efficiency is a concern, but no point in reading and parsing env var on every request.
That's as far as my Python skills go ;-)

2017-02-07 16:15 UTC, elevran commented on examples/apps/helloworld/app.py
>      response.set_cookie('version', json.dumps(service_version))
carry over form existing code, will fix

2017-02-07 16:16 UTC, elevran commented on examples/apps/helloworld/app.py
>      response.set_cookie('version', json.dumps(service_version))
k, will fix

2017-02-07 20:07 UTC, craigyam commented on examples/apps/helloworld/app.py
> +    response.set_cookie('version', json.dumps(version))
version is just a string now, right?  Don't need the json.dumps anymore (and can remove the import).

2017-02-07 20:07 UTC, craigyam commented on testing/kubernetes/helloworld.yaml
> +          value: v1
The version format for docker (and previous k8s) was version=v1.  The testing script looks for that when validating.

2017-02-07 20:07 UTC, craigyam commented on testing/kubernetes/helloworld.yaml
> +          value: v2
Same comment as line 92.

2017-02-08 15:10 UTC, rshriram reviewed
Everything other than removing the elasticsearch from K8S looks good. We use elasticsearch for gremlin tests.

2017-02-08 15:10 UTC, rshriram commented on testing/kubernetes/controlplane.yaml
> ----
Why remove this?

2017-02-08 15:27 UTC, rshriram approved these changes
Please comment out lines args, and elasticsearch_server in gateway (and later in bookinfo when you get to it. ). Otherwise lgtm

2017-02-08 15:42 UTC, elevran commented on testing/kubernetes/controlplane.yaml
> ----
will be adding rest of controplane functions once enabling the bookinfo example

2017-02-08 15:43 UTC, elevran commented
args and elastic_server are not used in helloworld example. Merging without those.

2017-02-08 15:44 UTC, merged