[WIP] first pass at strict_dns support for cf apps from registry
amalgam8/amalgam8 pull request #509
Opened 2017-02-08 21:18 UTC by GregHanson

finds instances from registry and build a static dns cluster for them in envoy.json file

2017-02-09 14:06 UTC, rshriram commented
Hold off on this please. It requires changes at Envoy level as well. This alone won't suffice

2017-02-27 18:13 UTC, rshriram commented
You might want to continue this again. Basically if we have CDS, and we return strict dns, this should work with the auto_host_rewrite option set in the route. See Envoy pr

2017-03-01 17:27 UTC, ijsnellf requested changes
Could be simplified a bit.

2017-03-01 17:27 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +	instanceByClusterMap := make(map[string][]*api.ServiceInstance)
`instancesByClusterMap`?

2017-03-01 17:27 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +	staticClusters := make(map[string]*api.Backend)
The logic from line 336 to 409 could be simplified by making `staticClusters` a set.

2017-03-01 17:27 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +	staticClusters := make(map[string]*api.Backend)
We never use the map value `*api.Backend`, so `staticClusters` would probably be more appropriate as a set: `map[string]struct{}`

2017-03-01 17:39 UTC, ijsnellf commented on sidecar/proxy/envoy/manager.go
> +		cluster.Type = "strict_dns"
`buildStaticCluster` function?

2017-03-01 19:47 UTC, ijsnellf approved these changes

2017-03-01 19:50 UTC, merged