Enable bookinfo automation for k8s native rules.
amalgam8/amalgam8 pull request #513
Opened 2017-02-13 23:39 UTC by craigyam

Update the bookinfo script and yaml files to use the k8s
native rules. Skip over Gremlin and traffic tests as they
are not supported with the k8s native rules.

2017-02-15 03:19 UTC, rshriram reviewed
I will let @elevran comment.

2017-02-15 03:19 UTC, rshriram commented on testing/kubernetes/bookinfo.yaml
> -          value: 5s
Let's remove elastic search as well. I don't think we have Gremlin assertion checks in the kubectl version.

2017-02-15 03:19 UTC, rshriram commented on testing/kubernetes/bookinfo.yaml
> -          value: 5s
That would mean setting A8_LOG to false

2017-02-15 03:19 UTC, rshriram commented on testing/kubernetes/install-kubernetes.sh
>          --allow-privileged --v=2
Why remove the dns?

2017-02-15 14:28 UTC, elevran reviewed
has overlap with #514, consider including only testing changes for this PR, not the example code

2017-02-15 14:28 UTC, elevran commented on testing/kubernetes/bookinfo.yaml
> -          value: 5s
Please see #514 for changed deployment files, integrating Shriram's comments as well.
I've ran through the entire walkthrough which can be used to confirm the testing scripts, if needed.

2017-02-15 14:28 UTC, elevran commented on testing/kubernetes/bookinfo.yaml
> -          value: 5s
The above changes are needed across all YAML files as in #514

2017-02-15 14:28 UTC, elevran commented on testing/test-scripts/k8s/default_routes.yaml
> +# Copyright 2017 IBM Corporation
we were working on these concurrently ;-(
May not be needed after a merge of #514 (which matches the bookinfo walkthrough files)

2017-02-15 14:29 UTC, elevran requested changes
Travis failure needs to be fixed as well

2017-02-16 21:04 UTC, craigyam commented on testing/kubernetes/install-kubernetes.sh
>          --allow-privileged --v=2
Saw some problems with the go http client timing out.  Removed the lines (to match what the previous config was) and they went away.

2017-02-19 08:21 UTC, elevran approved these changes

2017-02-19 08:21 UTC, elevran commented on .gitignore
>  examples/docker-helloworld-v1-v2-route-rules.json
can probably use docker-helloworld*.{json,yaml} as well

2017-02-22 22:17 UTC, craigyam commented on .gitignore
>  examples/docker-helloworld-v1-v2-route-rules.json
Done

2017-02-23 00:10 UTC, rshriram commented
@craigyam feel free to merge when you see fit.

2017-02-23 12:34 UTC, elevran approved these changes
LGTM.

2017-02-23 14:37 UTC, merged