K8s bookinfo files
amalgam8/amalgam8 pull request #514
Opened 2017-02-15 14:18 UTC by elevran

bookinfo deployment and routing rules
simplification in example generation

2017-02-15 14:35 UTC, elevran commented
Fixes #479

2017-02-16 15:17 UTC, craigyam requested changes

2017-02-16 15:17 UTC, craigyam commented on testing/test-scripts/bookinfo-jason-7s-delay.yaml
> +      - "varsion=v2"
Typo.  version=v2

2017-02-16 15:45 UTC, craigyam approved these changes

2017-02-16 16:14 UTC, merged